{
 "title": "Container Monitoring",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage [ Time Series ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{name!=\"\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage [ Bar ]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage [ Time Series ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{name!=\"\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage [ Bar ]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{name!=\"\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MQTT Messages Processed Per Second [Bar]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(subscriber_requests_total[$__rate_interval]))",
     "legendFormat": "Requests / Sec"
    }
   ]
  },
  {
   "title": "Message Processing Latencies [Milliseconds]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "subscriber_request_latency_milliseconds",
     "legendFormat": "P{{quantile}}"
    }
   ]
  }
 ]
}